server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: Root1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    drop-first: false
